"""Reconstruct a concrete-print PATH from a Rhino swept-tube OBJ mesh (side project).

The long-term goal is to lay measured LIDAR profiles along the print path of an *arbitrary* printed
structure (a path read from a file), the way the 3D heat map lays profiles along the serpentine
`compute_print_path_and_angle` path. This module is the first, deliberately isolated step: recover the
path *geometry* from a mesh generated by a real print, store it, and visualise it. No profile data yet.

**What the OBJ is** (validated on `ColumnData/Data/level1_typeA.obj`): a Rhino export where each `usemtl`
group is a swept-tube stroke — a structured quad grid of `R rings x RING_SIZE cross-section vertices`
(all faces quads, no caps). The stroke's centreline is the mean of each ring's vertices, so:

    print path  =  the ordered ring-centroids of each stroke.

Every stroke there is planar at a constant build height (the layer axis, `y` in that file, uniform layer
spacing) — one layer's dense meandering infill. Group order is only *roughly* build order, so we treat the
reliable ordering as build height, not group index.

Pipeline mirrors the main project (parse -> reconstruct -> cache NPZ -> view) without importing or being
imported by any analysis module: it depends only on numpy + pyvista (both already project dependencies).
The stored NPZ (centroids + per-point tangents/heading + metadata) is the reusable "coordinates file" a
future heat-map-style profile display would read; the tangents are the analogue of the heat map's per-point
tilt angle, ready for rotating profiles into the local print direction later.

Run the `# %%` cells at the bottom: cell 1 reconstructs + caches (one-time, ~1-3 min for a 1 GB OBJ),
cell 2 loads the cache and opens the interactive view.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, NamedTuple, Optional

import numpy as np
import pyvista as pv

logger = logging.getLogger(__name__)

# --- constants (Rhino sweep geometry / defaults) ---------------------------------------------------
DEFAULT_RING_SIZE = 11          # cross-section vertices per swept ring (the Rhino pipe resolution)
AXIS_NAMES = "xyz"              # index 0/1/2 -> coordinate name, for labels
_LAYER_ROUND_DECIMALS = 5       # round build-height values before de-duplicating into layers

# profile cladding (phase 2): hang measured profiles along the path
PROFILE_UNIT_TO_M = 1e-5        # profile unit (0.01 mm) in metres = the OBJ's native scale (see get_representative_profile)
DEFAULT_TARGET_PROFILES = 40000  # coarse-overview knob: approx cross-sections over the whole path (pass via target_profiles)
DEFAULT_PROFILE_POINTS = 25     # evenly re-index each profile down to this many points (interaction responsiveness)

# profile pool (phase 2d): many real profiles that vary smoothly along the path
DEFAULT_PROFILE_SAMPLES = 300   # pool size (100-500): different real cross-sections, smoothly varying
POOL_POINTS = 64                # points each pool profile is stored at (down-sampled per rib later)

# default dataset paths (relative to the repo root = the working directory when a cell is run)
DEFAULT_OBJ = Path("ColumnData/Data/level1_typeA.obj")
DEFAULT_NPZ = Path("ColumnData/PrintPath/level1_typeA_path.npz")
DEFAULT_PROFILE_NPZ = Path("ColumnData/PrintPath/representative_profile.npz")
DEFAULT_POOL_NPZ = Path("ColumnData/PrintPath/profile_pool.npz")


@dataclass
class PrintPath:
    """A reconstructed print path: one centreline polyline per stroke, plus geometry metadata.

    `strokes[i]` is an `(R_i, 3)` array of ordered centreline points; `tangents[i]` the matching unit
    heading at each point. `layer_axis` is the index (0/1/2) of the build/stacking axis.
    """

    strokes: list[np.ndarray]
    tangents: list[np.ndarray]
    layer_axis: int
    layer_height: float
    bead_radius: float
    source: str
    units: str = "unknown"

    @property
    def n_strokes(self) -> int:
        return len(self.strokes)

    @property
    def n_points(self) -> int:
        return int(sum(s.shape[0] for s in self.strokes))

    def bbox(self) -> tuple[np.ndarray, np.ndarray]:
        """(min, max) corner of all centreline points."""
        pts = np.vstack(self.strokes)
        return pts.min(axis=0), pts.max(axis=0)

    def summary(self) -> str:
        """One-line human-readable description (for logging / the workbench)."""
        lo, hi = self.bbox()
        return (f"PrintPath({self.n_strokes} strokes, {self.n_points} pts)  "
                f"layer_axis={AXIS_NAMES[self.layer_axis]}  layer_height={self.layer_height:.4f}  "
                f"bead_radius={self.bead_radius:.4f}  units={self.units}  "
                f"bbox={np.round(lo, 3)}..{np.round(hi, 3)}")


# --- parsing ---------------------------------------------------------------------------------------
def iter_obj_strokes(obj_path: Path | str) -> Iterator[tuple[np.ndarray, Optional[str]]]:
    """Stream an OBJ once, yielding `(vertices (N,3), first_face_line)` for each `usemtl` group.

    Only `v ` lines are parsed (normals/faces skipped, except each group's first `f` line, kept so the
    ring size can be derived). Streaming keeps peak memory to a single stroke, not the whole 1 GB file.
    """
    verts: Optional[list[tuple[float, float, float]]] = None
    face: Optional[str] = None
    with open(obj_path, "r") as fh:
        for line in fh:
            if line.startswith("usemtl"):
                if verts is not None:
                    yield np.asarray(verts, dtype=float), face
                verts, face = [], None
            elif line.startswith("v "):
                p = line.split()
                verts.append((float(p[1]), float(p[2]), float(p[3])))  # type: ignore[union-attr]
            elif face is None and line.startswith("f "):
                face = line
    if verts is not None:
        yield np.asarray(verts, dtype=float), face


def ring_size_from_face(face_line: Optional[str], default: int = DEFAULT_RING_SIZE) -> int:
    """Ring stride from a quad face `f a// b// c// d//`: |index(d) - index(a)| (offset cancels).

    e.g. `f 1 2 13 12` -> |12 - 1| = 11. Falls back to `default` if the face is missing/degenerate.
    """
    if not face_line:
        return default
    toks = face_line.split()[1:]
    if len(toks) < 4:
        return default
    a = int(toks[0].split("/")[0])
    d = int(toks[3].split("/")[0])
    stride = abs(d - a)
    return stride if stride > 0 else default


# --- reconstruction --------------------------------------------------------------------------------
def _tangents(centroids: np.ndarray) -> np.ndarray:
    """Unit heading at each centreline point (central differences; forward/backward at the ends)."""
    t = np.zeros_like(centroids)
    r = centroids.shape[0]
    if r >= 2:
        t[0] = centroids[1] - centroids[0]
        t[-1] = centroids[-1] - centroids[-2]
        if r > 2:
            t[1:-1] = centroids[2:] - centroids[:-2]
        nrm = np.linalg.norm(t, axis=1, keepdims=True)
        np.divide(t, nrm, out=t, where=nrm > 0)
    return t


def stroke_centerline(verts: np.ndarray, ring_size: int) -> tuple[np.ndarray, np.ndarray]:
    """Centreline `(R,3)` + unit tangents `(R,3)` of one swept stroke = mean of each ring's vertices."""
    n = verts.shape[0]
    if ring_size <= 0 or n % ring_size != 0:
        raise ValueError(f"{n} vertices not divisible by ring size {ring_size}")
    rings = verts.reshape(n // ring_size, ring_size, 3)
    centroids = rings.mean(axis=1)
    return centroids, _tangents(centroids)


def _ring_radius(verts: np.ndarray, ring_size: int, centroids: np.ndarray) -> float:
    """Mean distance from a stroke's ring vertices to their ring centroid (the nominal bead radius)."""
    rings = verts.reshape(centroids.shape[0], ring_size, 3)
    return float(np.linalg.norm(rings - centroids[:, None, :], axis=2).mean())


def _detect_layer_axis(strokes: list[np.ndarray]) -> int:
    """Build axis = the coordinate that varies least within a stroke (each stroke is one planar layer)."""
    ranges = np.array([s.ptp(axis=0) for s in strokes])  # (n_strokes, 3)
    return int(np.argmin(ranges.mean(axis=0)))


def _detect_layer_height(strokes: list[np.ndarray], axis: int) -> float:
    """Median spacing between distinct stroke build-heights (the layer height)."""
    vals = np.array([float(s[:, axis].mean()) for s in strokes])
    uniq = np.unique(np.round(vals, _LAYER_ROUND_DECIMALS))
    diffs = np.diff(np.sort(uniq))
    diffs = diffs[diffs > 1e-9]
    return float(np.median(diffs)) if diffs.size else 0.0


def reconstruct_path(obj_path: Path | str = DEFAULT_OBJ,
                     ring_size: Optional[int] = None,
                     units: str = "unknown") -> PrintPath:
    """Reconstruct the print path from a swept-tube OBJ (see module docstring).

    Args:
        obj_path: the mesh to read.
        ring_size: cross-section vertices per ring; None = auto-detect per stroke from its first face.
        units: recorded as metadata only (no rescaling); the file's native units are unknown.
    """
    strokes: list[np.ndarray] = []
    tangents: list[np.ndarray] = []
    radii: list[float] = []
    for verts, face in iter_obj_strokes(obj_path):
        if verts.size == 0:
            continue
        rs = ring_size or ring_size_from_face(face)
        if verts.shape[0] % rs != 0:
            logger.warning("stroke with %d vertices not divisible by ring size %d — skipping",
                           verts.shape[0], rs)
            continue
        cen, tan = stroke_centerline(verts, rs)
        strokes.append(cen)
        tangents.append(tan)
        radii.append(_ring_radius(verts, rs, cen))
    if not strokes:
        raise ValueError(f"no strokes parsed from {obj_path}")
    layer_axis = _detect_layer_axis(strokes)
    path = PrintPath(strokes, tangents, layer_axis,
                     _detect_layer_height(strokes, layer_axis),
                     float(np.mean(radii)), str(obj_path), units)
    logger.info("reconstructed %s", path.summary())
    return path


# --- storage (the reusable "coordinates file") -----------------------------------------------------
def save_path_npz(path: PrintPath, npz_path: Path | str = DEFAULT_NPZ) -> Path:
    """Save a PrintPath to a compressed NPZ: concatenated points/tangents + stroke offsets + metadata."""
    npz_path = Path(npz_path)
    npz_path.parent.mkdir(parents=True, exist_ok=True)
    lengths = np.array([s.shape[0] for s in path.strokes])
    offsets = np.concatenate([[0], np.cumsum(lengths)]).astype(np.int64)
    np.savez_compressed(
        npz_path,
        points=np.vstack(path.strokes).astype(np.float32),
        tangents=np.vstack(path.tangents).astype(np.float32),
        stroke_id=np.repeat(np.arange(lengths.size), lengths).astype(np.int32),
        stroke_offsets=offsets,
        layer_axis=np.int8(path.layer_axis),
        layer_height=np.float64(path.layer_height),
        bead_radius=np.float64(path.bead_radius),
        source=np.array(path.source),
        units=np.array(path.units),
    )
    logger.info("saved print path -> %s", npz_path)
    return npz_path


def load_path_npz(npz_path: Path | str = DEFAULT_NPZ) -> PrintPath:
    """Load a PrintPath previously written by `save_path_npz`."""
    with np.load(npz_path, allow_pickle=False) as d:
        offsets = d["stroke_offsets"]
        pts, tan = d["points"], d["tangents"]
        strokes = [pts[offsets[i]:offsets[i + 1]] for i in range(offsets.size - 1)]
        tangents = [tan[offsets[i]:offsets[i + 1]] for i in range(offsets.size - 1)]
        return PrintPath(strokes, tangents, int(d["layer_axis"]), float(d["layer_height"]),
                         float(d["bead_radius"]), str(d["source"]), str(d["units"]))


# --- visualisation ---------------------------------------------------------------------------------
def _combined_lines(strokes: list[np.ndarray]) -> tuple[np.ndarray, np.ndarray]:
    """Flatten strokes into one point array + a VTK polyline connectivity array (one line per stroke)."""
    points = np.vstack(strokes)
    cells: list[int] = []
    off = 0
    for s in strokes:
        n = s.shape[0]
        cells.append(n)
        cells.extend(range(off, off + n))
        off += n
    return points, np.array(cells)


def visualise_path(path: PrintPath, reveal: bool = True, show: bool = True,
                   cmap: str = "viridis", line_width: int = 2) -> "pv.Plotter":
    """Interactive PyVista view of the print path: polylines coloured by build height.

    When `reveal` (and a display is available) a slider hides strokes above a build-height threshold,
    so dragging it plays the build bottom-to-top. Returns the plotter (call `.show()` yourself if
    `show=False`, e.g. for a headless smoke test).
    """
    points, lines = _combined_lines(path.strokes)
    axis = path.layer_axis
    mesh = pv.PolyData(points)
    mesh.lines = lines
    mesh["height"] = points[:, axis]
    hmin, hmax = float(points[:, axis].min()), float(points[:, axis].max())

    # show() must pop a native interactive window (not a static inline trame image), or the reveal
    # slider is dead — same setting dataAnalysisSetup.py uses. Set before the Plotter reads the theme.
    if not pv.OFF_SCREEN:
        pv.global_theme.notebook = False
    plotter = pv.Plotter(window_size=[1280, 860])  # match the main 3D window
    bar = {"title": f"build height ({AXIS_NAMES[axis]})"}

    def draw(threshold: float) -> None:
        sub = mesh if threshold >= hmax else mesh.threshold((hmin, threshold), scalars="height")
        if sub.n_points == 0:
            plotter.remove_actor("path", reset_camera=False)  # nothing revealed yet
            return
        plotter.add_mesh(sub, scalars="height", cmap=cmap, clim=(hmin, hmax),
                         name="path", scalar_bar_args=bar, line_width=line_width)

    draw(hmax)
    if reveal and not pv.OFF_SCREEN:
        plotter.add_slider_widget(lambda v: draw(float(v)), rng=[hmin, hmax], value=hmax,
                                  title="reveal up to build height", style="modern")
    plotter.add_axes()
    plotter.camera.up = tuple(1.0 if i == axis else 0.0 for i in range(3))  # build axis points up
    if show and not pv.OFF_SCREEN:
        plotter.show()
    return plotter


# --- cladding: hang a measured profile along the path (phase 2) -------------------------------------
def get_representative_profile(cache_npz: Path | str = DEFAULT_PROFILE_NPZ,
                               processed_file: Optional[str] = None,
                               force: bool = False) -> np.ndarray:
    """One representative filament cross-section as local `(N, 2)` = (across, height) in profile units (0.01 mm).

    Picks the segment profile whose `widthOuter` is nearest the dataset median, keeps only its filament
    points (`~floorMask`, the zero-floor-levelled z), orders them across-track and centres both axes on their
    midpoints (so the rib sits centred on the ring-centroid). Cached to `cache_npz` so later runs skip the
    full processed-cache load. `profileLoading` / `datasetConfig` are imported lazily, so importing this
    module needs neither.
    """
    cache_npz = Path(cache_npz)
    if cache_npz.exists() and not force:
        with np.load(cache_npz, allow_pickle=False) as d:
            return d["profile_xy"]
    from datasetConfig import PROCESSED_FILE          # lazy: analysis stack only needed to (re)build the cache
    from profileLoading import load_profiles

    profiles = load_profiles(processed_file or PROCESSED_FILE)
    cand = [p for p in profiles
            if p.isSegment and p.floorMask is not None and p.widthOuter and int((~p.floorMask).sum()) >= 5]
    if not cand:
        raise ValueError("no segment filament profiles found in the processed cache")
    med = float(np.median([p.widthOuter for p in cand]))
    rep = min(cand, key=lambda p: abs(p.widthOuter - med))
    fil = ~rep.floorMask
    xy = np.column_stack((rep.x[fil], rep.z[fil])).astype(float)
    xy = xy[np.argsort(xy[:, 0])]                          # order across-track for a clean rib polyline
    xy[:, 0] -= 0.5 * (xy[:, 0].min() + xy[:, 0].max())    # centre across on the width midpoint
    xy[:, 1] -= 0.5 * (xy[:, 1].min() + xy[:, 1].max())    # centre height on the mid-bead
    cache_npz.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(cache_npz, profile_xy=xy.astype(np.float32), source=np.array(rep.name))
    logger.info("representative profile %r: %d filament pts, across-span %.0f, height-span %.0f (0.01 mm units)",
                rep.name, xy.shape[0], xy[:, 0].ptp(), xy[:, 1].ptp())
    return xy


def _filament_xy(p, points: int) -> np.ndarray:
    """One profile's filament cross-section as `(points, 2)` (across, height): sorted, centred, resampled."""
    fil = ~p.floorMask
    xy = np.column_stack((p.x[fil], p.z[fil])).astype(float)
    xy = xy[np.argsort(xy[:, 0])]
    xy[:, 0] -= 0.5 * (xy[:, 0].min() + xy[:, 0].max())    # centre across on the width midpoint
    xy[:, 1] -= 0.5 * (xy[:, 1].min() + xy[:, 1].max())    # centre height on the mid-bead
    return _resample_profile(xy, points)


def get_profile_samples(n_samples: int = DEFAULT_PROFILE_SAMPLES, points: int = POOL_POINTS,
                        cache_npz: Path | str = DEFAULT_POOL_NPZ,
                        processed_file: Optional[str] = None, force: bool = False) -> np.ndarray:
    """A POOL of real filament cross-sections as `(n_samples, points, 2)` local (across, height), profile units.

    Takes a CONTIGUOUS run of measured profiles (the middle of the longest filament run in the cache), so
    consecutive pool entries are naturally similar ("similar if just after each other"); each is centred and
    resampled to `points`. Cached to `cache_npz` (rebuilt if the cached shape differs). `profileLoading` /
    `datasetConfig` are imported lazily, so importing this module needs neither.
    """
    cache_npz = Path(cache_npz)
    if cache_npz.exists() and not force:
        with np.load(cache_npz, allow_pickle=False) as d:
            pool = d["pool"]
        if pool.shape == (n_samples, points, 2):
            return pool
    from datasetConfig import PROCESSED_FILE          # lazy: analysis stack only needed to (re)build the cache
    from profileLoading import load_profiles

    profiles = load_profiles(processed_file or PROCESSED_FILE)
    has_fil = np.array([p.floorMask is not None and int((~p.floorMask).sum()) >= 5 for p in profiles])
    # longest contiguous run of filament profiles (consecutive scans of one printed stretch -> smooth)
    best_len = best_start = cur = start = 0
    for i, f in enumerate(has_fil):
        cur = cur + 1 if f else 0
        start = start if f and cur > 1 else i
        if cur > best_len:
            best_len, best_start = cur, start
    if best_len < n_samples:
        raise ValueError(f"longest filament run is {best_len} profiles (< n_samples={n_samples})")
    off = best_start + (best_len - n_samples) // 2       # centre the window in the run (skip startup/rupture ends)
    pool = np.stack([_filament_xy(profiles[off + i], points) for i in range(n_samples)]).astype(np.float32)
    cache_npz.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(cache_npz, pool=pool, start=np.int64(off))
    logger.info("profile pool: %d samples x %d pts from run [%d,%d), width %.0f..%.0f (0.01 mm)",
                n_samples, points, off, off + n_samples,
                np.ptp(pool[:, :, 0], axis=1).min(), np.ptp(pool[:, :, 0], axis=1).max())
    return pool


def _resample_profile(profile_xy: np.ndarray, n: Optional[int]) -> np.ndarray:
    """Evenly re-index a profile down to ~`n` points (endpoints kept, order preserved); None/>=len -> unchanged."""
    xy = np.asarray(profile_xy, dtype=float)
    m = xy.shape[0]
    if not n or n >= m:
        return xy
    return xy[np.unique(np.linspace(0, m - 1, n).round().astype(int))]


def _arclength(cen: np.ndarray) -> np.ndarray:
    """Cumulative arc length `(N,)` along a stroke's centroids (s[0]=0)."""
    return np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(cen, axis=0), axis=1))])


def _resample_stroke(cen: np.ndarray, s: np.ndarray, spacing: float,
                     tangent_steps: int = 1) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """EQUIDISTANT points along the stroke polyline + central-difference tangents + their arc-length `d`.

    Positions are interpolated at arc-length multiples of `spacing` (so ribs are evenly spaced even across
    long/coarse centroid gaps, not snapped to existing centroids). The tangent is a central difference over
    `tangent_steps` of these equidistant points — a fixed physical span that follows the local print
    direction through corners (never the across-the-U-turn chord that a centroid-window gives).
    """
    if s[-1] <= 0:
        return cen[:1].copy(), np.zeros((1, 3)), np.zeros(1)
    d = np.arange(0.0, s[-1], spacing)
    p = np.column_stack([np.interp(d, s, cen[:, k]) for k in range(3)])
    n = p.shape[0]
    lo = np.clip(np.arange(n) - tangent_steps, 0, n - 1)
    hi = np.clip(np.arange(n) + tangent_steps, 0, n - 1)
    return p, p[hi] - p[lo], d


def _selected_stroke_indices(path: PrintPath, strokes: Optional[object]) -> list[int]:
    """Stroke indices to clad: all of them (strokes=None) or the valid entries of the given indices/range."""
    if strokes is None:
        return list(range(path.n_strokes))
    return [i for i in strokes if 0 <= i < path.n_strokes]


class Cladding(NamedTuple):
    """Result of `clad_path`: rib points + line cells, an optional swept-surface face array, and per-point
    `along` (global along-path distance, for the reveal) and `defect` (0/1) scalars."""
    points: np.ndarray      # (M, 3) all rib points
    rib_cells: np.ndarray   # VTK polyline connectivity, one line per rib
    faces: np.ndarray       # VTK quad connectivity of the swept surface (empty if build_surface=False)
    along: np.ndarray       # (M,) global along-path distance per point
    defect: np.ndarray      # (M,) 0/1 defect flag per point


def clad_path(path: PrintPath, profile_xy: np.ndarray, arc_spacing: Optional[float] = None,
              target_profiles: Optional[int] = None, scale: str | float = "fit", height_frac: float = 1.0,
              profile_points: Optional[int] = DEFAULT_PROFILE_POINTS, strokes: Optional[object] = None,
              tangent_steps: int = 1, n_defects: int = 0, defect_length: float = 0.15,
              build_surface: bool = False) -> "Cladding":
    """Place profile(s) as ribs along the path; returns a `Cladding` (points, rib_cells, faces, along, defect).

    `profile_xy` is either a single cross-section `(N,2)` (reused everywhere) or a POOL `(M,P,2)` of many —
    the pool is mapped monotonically by along-path fraction, so adjacent ribs get similar profiles and the
    whole pool is shown once across the path. Each stroke is resampled to EQUIDISTANT arc-length points
    (`_resample_stroke`); at each, the profile's local (across, height) is rotated into the print frame
    (`up` = build axis, `across` = up x tangent) and scaled. `scale="fit"` sets ONE global scale so the
    median profile height equals the layer height (preserving real height variation between profiles); a
    float overrides.

    Spacing precedence: explicit `arc_spacing` -> `total_len/target_profiles` (coarse overview) -> one bead
    width. `n_defects` ribs-runs of length ~`defect_length` (obj units), evenly spaced along the path, are
    flattened (height 0) and flagged as defects. `build_surface` also emits `faces` = a quad grid connecting
    consecutive ribs WITHIN each stroke (the swept bead surface; never bridges layers). Ribs at degenerate
    tangents are skipped.
    """
    axis = path.layer_axis
    up = np.zeros(3)
    up[axis] = 1.0
    sel = _selected_stroke_indices(path, strokes)

    # normalise to a pool (M, n, 2), resample each entry, and pre-scale with ONE global fit scale
    pool_in = np.asarray(profile_xy, dtype=float)
    pool_in = pool_in[None] if pool_in.ndim == 2 else pool_in
    pool = np.stack([_resample_profile(pool_in[m], profile_points) for m in range(pool_in.shape[0])])
    n_pool, n = pool.shape[0], pool.shape[1]
    ref_span = float(np.median(np.ptp(pool[:, :, 1], axis=1))) or 1.0
    k = height_frac * path.layer_height / ref_span if scale == "fit" else float(scale)
    pool_a, pool_h = pool[:, :, 0] * k, pool[:, :, 1] * k          # (n_pool, n) local coords in obj units

    total_len = sum(float(_arclength(path.strokes[i])[-1]) for i in sel) or 1.0
    if arc_spacing is None:
        arc_spacing = max(total_len / target_profiles, 1e-9) if target_profiles else 2.0 * path.bead_radius
    centres = (np.arange(n_defects) + 0.5) / n_defects * total_len if n_defects > 0 else np.empty(0)
    half = 0.5 * defect_length

    all_pts: list[np.ndarray] = []
    all_along: list[np.ndarray] = []
    all_defect: list[np.ndarray] = []
    all_faces: list[np.ndarray] = []
    cells: list[int] = []
    off = 0
    path_offset = 0.0                                     # running along-path distance across selected strokes
    for i in sel:
        cen = path.strokes[i]
        if cen.shape[0] < 2:
            continue
        s = _arclength(cen)
        base, t, d = _resample_stroke(cen, s, arc_spacing, tangent_steps)  # equidistant positions + tangents
        tn = np.linalg.norm(t, axis=1)
        keep = tn > 1e-12
        base, t, d = base[keep], t[keep], d[keep]
        if base.shape[0]:
            t = t / np.linalg.norm(t, axis=1, keepdims=True)
            across = np.cross(np.broadcast_to(up, t.shape), t)   # horizontal, perpendicular to the heading
            an = np.linalg.norm(across, axis=1)
            keep = an > 1e-12
            base, across, d = base[keep], across[keep] / an[keep, None], d[keep]
        if base.shape[0]:
            along = path_offset + d                                # (P,) global along-path distance per rib
            pidx = (np.clip(np.round(along / total_len * (n_pool - 1)), 0, n_pool - 1).astype(int)
                    if n_pool > 1 else np.zeros(along.shape[0], int))
            a_rib, h_rib = pool_a[pidx], pool_h[pidx].copy()      # (P, n) per-rib profile
            is_def = (np.abs(along[:, None] - centres[None, :]).min(axis=1) <= half
                      if centres.size else np.zeros(along.shape[0], bool))
            h_rib[is_def] = 0.0                                    # defect = flat line at the centroid level
            pts = (base[:, None, :] + a_rib[:, :, None] * across[:, None, :]
                   + h_rib[:, :, None] * up[None, None, :]).reshape(base.shape[0] * n, 3)
            all_pts.append(pts)
            all_along.append(np.repeat(along, n))
            all_defect.append(np.repeat(is_def.astype(float), n))
            p_ribs = base.shape[0]
            stroke_start = off
            for _ in range(p_ribs):                               # one polyline cell per placed profile
                cells.append(n)
                cells.extend(range(off, off + n))
                off += n
            if build_surface and p_ribs >= 2:                     # quad grid over this stroke's ribs
                r = np.arange(p_ribs - 1)[:, None]
                j = np.arange(n - 1)[None, :]
                i00 = stroke_start + r * n + j                    # (p_ribs-1, n-1) lower-left of each quad
                quads = np.stack([np.full(i00.shape, 4), i00, i00 + 1, i00 + n + 1, i00 + n], axis=-1)
                all_faces.append(quads.reshape(-1))
        path_offset += float(s[-1])
    if not all_pts:
        raise ValueError("no ribs placed (empty selection or degenerate path)")
    faces = np.concatenate(all_faces) if all_faces else np.empty(0, dtype=int)
    return Cladding(np.vstack(all_pts), np.array(cells), faces,
                    np.concatenate(all_along), np.concatenate(all_defect))


def _colour_args(colour: str, cmap: str, axis: int, amin: float, amax: float,
                 hmin: float, hmax: float) -> tuple:
    """(scalar name, cmap, clim, show_bar, bar title) for a colour mode: grey/defect | height | along."""
    if colour in ("grey", "defect"):
        return "cat", ["lightgrey", "red"], (0.0, 1.0), False, None
    if colour == "along":
        return "along", cmap, (amin, amax), True, "along-path distance (print order)"
    return "height", cmap, (hmin, hmax), True, f"build height ({AXIS_NAMES[axis]})"


def visualise_cladding(path: PrintPath, profile_xy: np.ndarray, show: bool = True, cmap: str = "viridis",
                       line_width: int = 2, colour_by: str = "height", show_path: bool = False,
                       path_colour: str = "red", path_width: int = 3, sequential: bool = False,
                       surface: bool = False, surface_style: str = "ribs", surface_opacity: float = 0.4,
                       defect_markers: bool = False, defect_pillars: bool = False,
                       opacity_slider: bool = False, marker_radius: Optional[float] = None,
                       **clad_kwargs) -> "pv.Plotter":
    """Interactive view of the path clad with `profile_xy` as ribs (and, when `surface`, a swept bead surface).

    `colour_by`: "height"/"along" (viridis + bar) or "defect" (grey profiles, red defects). `surface` adds
    the connecting swept surface (use `surface_opacity=1.0` for a fast OPAQUE whole-object view; <1 is
    translucent). In-plot toggle BUTTONS: style (grid edges), colour (grey<->height), and — when defects
    exist — "defect markers" (red spheres at each defect) and "defect pillars" (full-height red lines through
    each defect, visible from any angle). `opacity_slider` adds a slider dimming the bead so defects pop;
    `sequential` adds a bottom reveal slider (print order). `show_path` draws the centroid print path in
    `path_colour`. Extra kwargs pass to `clad_path`. Returns the plotter (call `.show()` if False).
    """
    clad = clad_path(path, profile_xy, build_surface=surface, **clad_kwargs)
    points, along, defect = clad.points, clad.along, clad.defect
    axis = path.layer_axis
    height = points[:, axis]
    amin, amax = float(along.min()), float(along.max())
    hmin, hmax = float(height.min()), float(height.max())
    n = int(clad.rib_cells[0]) if clad.rib_cells.size else 1

    rib_mesh = pv.PolyData(points)
    rib_mesh.lines = clad.rib_cells
    surf_mesh = pv.PolyData(points, clad.faces) if surface and clad.faces.size else None
    for m in (rib_mesh, surf_mesh):                          # every mesh carries all three scalars
        if m is not None:
            m["along"], m["cat"], m["height"] = along, defect, height
    has_def = float(defect.sum()) > 0

    centres = np.empty((0, 3))                               # one 3-D centre per contiguous defect run
    if has_def:
        rib_def = defect.reshape(-1, n)[:, 0] > 0
        rib_ctr = points.reshape(-1, n, 3).mean(axis=1)
        di = np.where(rib_def)[0]
        centres = np.array([rib_ctr[r].mean(axis=0) for r in np.split(di, np.where(np.diff(di) > 1)[0] + 1)])

    if not pv.OFF_SCREEN:
        pv.global_theme.notebook = False                     # native window (as visualise_path / dataAnalysisSetup)
    plotter = pv.Plotter(window_size=[1280, 860])

    if show_path:                                            # the centroid print path, drawn once and kept
        sel = _selected_stroke_indices(path, clad_kwargs.get("strokes"))
        p_pts, p_lines = _combined_lines([path.strokes[i] for i in sel])
        p_mesh = pv.PolyData(p_pts)
        p_mesh.lines = p_lines
        plotter.add_mesh(p_mesh, color=path_colour, name="path", line_width=path_width)

    init_colour = "grey" if colour_by == "defect" else colour_by
    base_style = "ribs" if surface_style == "edges" else surface_style  # style when "grid edges" is OFF ("ribs"|"surface")
    state = {"threshold": amax, "style": surface_style, "colour": init_colour, "opacity": surface_opacity}
    handles: dict = {"surface": None, "ribs": None}          # live actor refs (for the opacity slider)

    def _clip(m: "pv.PolyData"):
        t = state["threshold"]
        return m if t >= amax else m.threshold((amin, t), scalars="along")

    def redraw() -> None:
        handles["surface"] = handles["ribs"] = None
        scal, cmapc, climc, bar, title = _colour_args(state["colour"], cmap, axis, amin, amax, hmin, hmax)
        if not bar:                                          # categorical: drop any stale gradient bar
            for tt in list(plotter.scalar_bars.keys()):
                try:
                    plotter.remove_scalar_bar(tt)
                except (KeyError, StopIteration, RuntimeError):
                    pass
        if state["threshold"] <= amin:                       # far-left reveal: nothing yet
            for nm in ("surface", "ribs", "defect"):
                plotter.remove_actor(nm, reset_camera=False)
            return
        op = state["opacity"]
        edges = surf_mesh is not None and state["style"] == "edges"
        if surf_mesh is not None:                            # the connecting bead surface
            sub = _clip(surf_mesh)
            if sub.n_points:
                handles["surface"] = plotter.add_mesh(
                    sub, scalars=scal, cmap=cmapc, clim=climc, name="surface", opacity=op, show_edges=edges,
                    edge_color="dimgray", show_scalar_bar=bar, scalar_bar_args={"title": title} if bar else None)
        if surf_mesh is None or state["style"] == "ribs":    # solid individual profiles
            sub = _clip(rib_mesh)
            if sub.n_points:
                ribs_bar = bar and surf_mesh is None
                handles["ribs"] = plotter.add_mesh(
                    sub, scalars=scal, cmap=cmapc, clim=climc, name="ribs", line_width=line_width,
                    opacity=op if surf_mesh is not None else 1.0,
                    show_scalar_bar=ribs_bar, scalar_bar_args={"title": title} if ribs_bar else None)
        else:
            plotter.remove_actor("ribs", reset_camera=False)
        if has_def:                                          # defects always red + opaque, on top
            dsub = _clip(rib_mesh.threshold((0.5, 1.0), scalars="cat"))
            if dsub.n_points:
                plotter.add_mesh(dsub, color="red", name="defect", line_width=line_width + 2)
            else:
                plotter.remove_actor("defect", reset_camera=False)
        try:                                                 # legend only in the categorical (grey) mode
            plotter.remove_legend()
        except (ValueError, AttributeError, RuntimeError):
            pass
        if state["colour"] in ("grey", "defect"):
            entries = [["profile", "lightgrey"]] + ([["defect", "red"]] if has_def else []) \
                + ([["print path", path_colour]] if show_path else [])
            plotter.add_legend(entries, bcolor="white", size=(0.16, 0.12), loc="upper right")

    redraw()

    m_actor = p_actor = None                                 # defect markers/pillars: built once, visibility toggled
    if centres.shape[0]:
        radius = marker_radius if marker_radius else 8.0 * path.bead_radius
        glyph = pv.PolyData(centres).glyph(geom=pv.Sphere(radius=radius), scale=False, orient=False)
        m_actor = plotter.add_mesh(glyph, color="red", name="markers")
        m_actor.visibility = bool(defect_markers)
        pil_pts: list = []
        pil_lines: list = []
        for c in centres:                                    # full-height red line at each defect's x-z
            lo = c.copy(); lo[axis] = hmin
            hi = c.copy(); hi[axis] = hmax
            j = len(pil_pts); pil_pts += [lo, hi]; pil_lines += [2, j, j + 1]
        pil = pv.PolyData(np.array(pil_pts))
        pil.lines = np.array(pil_lines)
        p_actor = plotter.add_mesh(pil, color="red", name="pillars", line_width=4)
        p_actor.visibility = bool(defect_pillars)

    if not pv.OFF_SCREEN:
        bx, by, bdy = 12, 12, 36                             # stacked bottom-left checkboxes
        if surf_mesh is not None:
            plotter.add_checkbox_button_widget(
                lambda v: (state.update(style="edges" if v else base_style), redraw()),
                value=surface_style == "edges", position=(bx, by), size=26, color_on="black")
            plotter.add_text("grid edges", position=(bx + 34, by + 2), font_size=9, name="t_style")
            by += bdy
            plotter.add_checkbox_button_widget(
                lambda v: (state.update(colour="height" if v else "grey"), redraw()),
                value=state["colour"] == "height", position=(bx, by), size=26, color_on="black")
            plotter.add_text("height colour", position=(bx + 34, by + 2), font_size=9, name="t_colour")
            by += bdy
        if m_actor is not None:
            plotter.add_checkbox_button_widget(lambda v, a=m_actor: setattr(a, "visibility", bool(v)),
                                               value=bool(defect_markers), position=(bx, by), size=26, color_on="red")
            plotter.add_text("defect markers", position=(bx + 34, by + 2), font_size=9, name="t_mark")
            by += bdy
        if p_actor is not None:
            plotter.add_checkbox_button_widget(lambda v, a=p_actor: setattr(a, "visibility", bool(v)),
                                               value=bool(defect_pillars), position=(bx, by), size=26, color_on="red")
            plotter.add_text("defect pillars", position=(bx + 34, by + 2), font_size=9, name="t_pill")
        if sequential:                                       # bottom sliders (clear of the upper-right legend)
            plotter.add_slider_widget(lambda v: (state.update(threshold=float(v)), redraw()),
                                      rng=[amin, amax], value=amax, title="reveal along print path",
                                      style="modern", pointa=(0.30, 0.12), pointb=(0.72, 0.12))
        if opacity_slider and surf_mesh is not None:
            def _set_opacity(v: float) -> None:
                state["opacity"] = float(v)                  # live property change -> no re-render, no lag
                for k in ("surface", "ribs"):
                    if handles.get(k) is not None:
                        handles[k].prop.opacity = float(v)
            plotter.add_slider_widget(_set_opacity, rng=[0.05, 1.0], value=surface_opacity,
                                      title="bead opacity", style="modern", pointa=(0.30, 0.035), pointb=(0.72, 0.035))
    logger.info("cladding: %d ribs, %d points, surface=%s, defects=%d, path=%s, sequential=%s",
                rib_mesh.n_lines, rib_mesh.n_points, surface, centres.shape[0], show_path, sequential)
    plotter.add_axes()
    plotter.camera.up = tuple(1.0 if i == axis else 0.0 for i in range(3))
    if show and not pv.OFF_SCREEN:
        plotter.show()
    return plotter


# %% reconstruct the print path from the OBJ and cache it as NPZ  (run once; ~1-3 min for a 1 GB file)
# Self-import bootstraps every definition, so this cell can be run first in a fresh kernel.
if __name__ == "__main__":
    import logging

    import printPathFromObj as ppo

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    _path = ppo.reconstruct_path(ppo.DEFAULT_OBJ)
    print(_path.summary())
    ppo.save_path_npz(_path, ppo.DEFAULT_NPZ)


# %% load the cached path and visualise it  (colour by build height; slider reveals bottom -> top)
if __name__ == "__main__":
    import printPathFromObj as ppo

    _path = ppo.load_path_npz(ppo.DEFAULT_NPZ)
    print(_path.summary())
    ppo.visualise_path(_path)


# %% clad the WHOLE object  (overview: OPAQUE swept surface + defect aids, lag-safe)
# The whole ~4.3 km path as a solid opaque bead surface (opaque => no transparency lag). 12 defects are
# injected. Buttons (bottom-left): grid edges, height<->grey colour, defect markers (red spheres), defect
# pillars (full-height red lines). Slider (bottom): "bead opacity" dims the grey bead so defects pop.
# Coarse spacing (0.06 / 6 pts ~0.36M quads) keeps it responsive; raise for detail, lower if it lags.
if __name__ == "__main__":
    import logging

    import printPathFromObj as ppo

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    _path = ppo.load_path_npz(ppo.DEFAULT_NPZ)
    _pool = ppo.get_profile_samples()                 # (300, 64, 2) real profiles; cached after first run
    ppo.visualise_cladding(_path, _pool, arc_spacing=0.06, profile_points=6, n_defects=12,
                           surface=True, surface_style="surface", surface_opacity=1.0, colour_by="height",
                           show_path=True, path_colour="blue", defect_markers=True, defect_pillars=True,
                           opacity_slider=True)


# %% clad a FOCUSED REGION with a CONNECTING SURFACE  (detail: translucent bead surface + ribs + buttons)
# A pool of ~300 real profiles varies smoothly along the path; ~5 flat red defects are injected. A swept
# surface connects the profiles so you can see which form the path. Buttons (bottom-left): grid edges,
# height<->grey colour, defect markers (red spheres). Sliders (bottom): "reveal along print path" (print
# order) and "bead opacity" (dim the bead so defects pop). Blue print path. Tune strokes / n_defects.
if __name__ == "__main__":
    import printPathFromObj as ppo

    _path = ppo.load_path_npz(ppo.DEFAULT_NPZ)
    _pool = ppo.get_profile_samples()                 # (300, 64, 2) real profiles; cached after first run
    ppo.visualise_cladding(_path, _pool, strokes=range(240, 252), profile_points=30, colour_by="defect",
                           n_defects=5, defect_length=0.15, surface=True, surface_style="ribs",
                           show_path=True, path_colour="blue", sequential=True,
                           defect_markers=True, opacity_slider=True)

# %%
